package com.group21.sneakerhub.helper;

import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.group21.sneakerhub.model.Product;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

public class firebaseDatabasePopulator implements IDatabasePopulator {
    private final FirebaseFirestore db = FirebaseFirestore.getInstance();;

    @Override
    public void populate() {

        CollectionReference products = db.collection("Products");
        Map<Long,Product> productsMap = new HashMap<Long,Product>();
        // continue add onto existing data in the database
        long id = 22;
        long initialId = id;
        // Air Jordan shoes
        productsMap.put(id,new Product("Air Jordan 7", id, 1, 445.00, "Grey", new ArrayList<Integer>(Arrays.asList(7 ,8, 12)), 4.52352, 34, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Designed by Tinker Hatfield, the AJ7 covered up the Air window in the heel and removed exterior Nike branding altogether, reflecting the growing independence of Air Jordan.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), true));
        productsMap.put(id,new Product("Air Jordan 7", id, 1, 445.00, "White", new ArrayList<Integer>(Arrays.asList(7 ,8)), 4.12313, 10, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Designed by Tinker Hatfield, the AJ7 covered up the Air window in the heel and removed exterior Nike branding altogether, reflecting the growing independence of Air Jordan.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));
        productsMap.put(id,new Product("Air Jordan 7", id, 1, 445.00, "Blue", new ArrayList<Integer>(Arrays.asList(8,13)), 4, 1, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Designed by Tinker Hatfield, the AJ7 covered up the Air window in the heel and removed exterior Nike branding altogether, reflecting the growing independence of Air Jordan.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));

        productsMap.put(id,new Product("Air Jordan 8", id, 1, 420.99, "Yellow", new ArrayList<Integer>(Arrays.asList(7 ,8)), 4.113, 14, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Jordan 8 is Michael Jordan's eighth signature basketball shoe. It released in 1993 during MJ's “Three-Peat” Championship season. Created by Tinker Hatfield, this is the last shoe that Jordan wore before his first retirement.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), true));
        productsMap.put(id,new Product("Air Jordan 8", id, 1, 420.99, "Blue", new ArrayList<Integer>(Arrays.asList(7 ,8)), 4.7413, 51, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Jordan 8 is Michael Jordan's eighth signature basketball shoe. It released in 1993 during MJ's “Three-Peat” Championship season. Created by Tinker Hatfield, this is the last shoe that Jordan wore before his first retirement.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));
        productsMap.put(id,new Product("Air Jordan 8", id, 1, 420.99, "Grey", new ArrayList<Integer>(Arrays.asList(7 ,8)), 3.15, 9, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Jordan 8 is Michael Jordan's eighth signature basketball shoe. It released in 1993 during MJ's “Three-Peat” Championship season. Created by Tinker Hatfield, this is the last shoe that Jordan wore before his first retirement.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));

        productsMap.put(id,new Product("Air Jordan 11", id, 1, 555.50, "Red", new ArrayList<Integer>(Arrays.asList(11,12,13)), 3.000, 9, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Jordan 11 debuted in 1995 as Michael Jordan's 11th signature sneaker. Designed by Tinker Hatfield, the Jordan 11 was the first Air Jordan to feature patent leather and carbon fiber in addition to cordura nylon.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), true));
        productsMap.put(id,new Product("Air Jordan 11", id, 1, 555.50, "Blue", new ArrayList<Integer>(Arrays.asList(7 ,12,13)), 3.1412, 19, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Jordan 11 debuted in 1995 as Michael Jordan's 11th signature sneaker. Designed by Tinker Hatfield, the Jordan 11 was the first Air Jordan to feature patent leather and carbon fiber in addition to cordura nylon.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));
        productsMap.put(id,new Product("Air Jordan 11", id, 1, 555.50, "Grey", new ArrayList<Integer>(Arrays.asList(7 ,8,10)), 2.451, 10, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Jordan 11 debuted in 1995 as Michael Jordan's 11th signature sneaker. Designed by Tinker Hatfield, the Jordan 11 was the first Air Jordan to feature patent leather and carbon fiber in addition to cordura nylon.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));

        // Nike shoes
        productsMap.put(id,new Product("Air Force 1", id, 2, 180.99, "White", new ArrayList<Integer>(Arrays.asList(9,10)), 4.87, 39, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Nike Air Force 1 remains a popular retro shoe to this day. The Air Force 1 features an upper that is most frequently dressed in leather, a large Swoosh across the lateral and medial sides, perforated toe boxes, metal lace dubraes, and an Air-encapsulated midsole with signature “AIR” text near the rear.", new ArrayList<>(Arrays.asList("Low-top")), true));
        productsMap.put(id,new Product("Air Force 1", id, 2, 180.99, "Black", new ArrayList<Integer>(Arrays.asList(9,10,11)), 4.63, 25, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Nike Air Force 1 remains a popular retro shoe to this day. The Air Force 1 features an upper that is most frequently dressed in leather, a large Swoosh across the lateral and medial sides, perforated toe boxes, metal lace dubraes, and an Air-encapsulated midsole with signature “AIR” text near the rear.", new ArrayList<>(Arrays.asList("Low-top")), false));
        productsMap.put(id,new Product("Air Force 1", id, 2, 180.99, "Red", new ArrayList<Integer>(Arrays.asList(9,10,11)), 3.14, 12, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Nike Air Force 1 remains a popular retro shoe to this day. The Air Force 1 features an upper that is most frequently dressed in leather, a large Swoosh across the lateral and medial sides, perforated toe boxes, metal lace dubraes, and an Air-encapsulated midsole with signature “AIR” text near the rear.", new ArrayList<>(Arrays.asList("Low-top")), false));

        productsMap.put(id,new Product("Air Max 90", id, 2, 209.99, "White", new ArrayList<Integer>(Arrays.asList(8,12)), 2.42, 41, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "One of the most popular Air Max sneakers of all-time, the Nike Air Max 90 was originally released in 1990. They feature a bigger Air-Sole unit than their predecessor by eliminating the foam between the outsole.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Air Max 90", id, 2, 209.99, "Black", new ArrayList<Integer>(Arrays.asList(8,9,12)), 2.42, 11, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "One of the most popular Air Max sneakers of all-time, the Nike Air Max 90 was originally released in 1990. They feature a bigger Air-Sole unit than their predecessor by eliminating the foam between the outsole.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Air Max 90", id, 2, 209.99, "Grey", new ArrayList<Integer>(Arrays.asList(8,10,12)), 3.4, 2, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "One of the most popular Air Max sneakers of all-time, the Nike Air Max 90 was originally released in 1990. They feature a bigger Air-Sole unit than their predecessor by eliminating the foam between the outsole.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Air Max 95", id, 2, 219.99, "White", new ArrayList<Integer>(Arrays.asList(7,9,12)), 2.32, 56, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The release of the Air Max 95 marked a huge shift in the sneaker landscape. Debuting as a performance runner, the sneak stood out from the crowd with its distinct rippled effect to the sidewalls along with its use of bright and neon colours.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Air Max 95", id, 2, 219.99, "Black", new ArrayList<Integer>(Arrays.asList(7,9,12)), 2.54, 23, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The release of the Air Max 95 marked a huge shift in the sneaker landscape. Debuting as a performance runner, the sneak stood out from the crowd with its distinct rippled effect to the sidewalls along with its use of bright and neon colours.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Air Max 95", id, 2, 219.99, "Red", new ArrayList<Integer>(Arrays.asList(7,8,9,12)), 3.15, 12, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The release of the Air Max 95 marked a huge shift in the sneaker landscape. Debuting as a performance runner, the sneak stood out from the crowd with its distinct rippled effect to the sidewalls along with its use of bright and neon colours.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Air Max 97", id, 2, 205.99, "White", new ArrayList<Integer>(Arrays.asList(7,9,12)), 4.914, 12, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Max 97 is a Nike running shoe designed by Christian Tresser. It was inspired by Japan's high-speed Bullet Trains and features a mix of leather, foam, and full-length visible Air.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Air Max 97", id, 2, 205.99, "Black", new ArrayList<Integer>(Arrays.asList(7)), 4.334, 10, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Max 97 is a Nike running shoe designed by Christian Tresser. It was inspired by Japan's high-speed Bullet Trains and features a mix of leather, foam, and full-length visible Air.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Air Max 97", id, 2, 205.99, "Grey", new ArrayList<Integer>(Arrays.asList(7,8,9,12)), 4.81111, 11, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Air Max 97 is a Nike running shoe designed by Christian Tresser. It was inspired by Japan's high-speed Bullet Trains and features a mix of leather, foam, and full-length visible Air.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Air Max 270", id, 2, 210.50, "White", new ArrayList<Integer>(Arrays.asList(7,9,10,11,12)), 3.6141, 14, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "A Nike Sportswear lifestyle sneaker, the Air Max 270 is an unique design that pairs the ultimate Air Max comfort with a modern-edge silhouette. Inspired by classic Air Max models from the 90s, this unique shoe provides extreme performance as well as iconic styling.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Air Max 270", id, 2, 210.50, "Black", new ArrayList<Integer>(Arrays.asList(7,9,10,11,12)), 1.51534, 4, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "A Nike Sportswear lifestyle sneaker, the Air Max 270 is an unique design that pairs the ultimate Air Max comfort with a modern-edge silhouette. Inspired by classic Air Max models from the 90s, this unique shoe provides extreme performance as well as iconic styling.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Air Max 270", id, 2, 210.50, "Red", new ArrayList<Integer>(Arrays.asList(7,11,12)), 3.141, 19, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "A Nike Sportswear lifestyle sneaker, the Air Max 270 is an unique design that pairs the ultimate Air Max comfort with a modern-edge silhouette. Inspired by classic Air Max models from the 90s, this unique shoe provides extreme performance as well as iconic styling.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Vapormax", id, 2, 269.99, "White", new ArrayList<Integer>(Arrays.asList(11,12)), 4.14, 28, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "If you're looking for a lightweight running shoe, the VaporMax Flyknit from Nike delivers with flying colors. It's comfortable and versatile, making it a value-oriented trainer.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Vapormax", id, 2, 269.99, "Black", new ArrayList<Integer>(Arrays.asList(11,12)), 3.24, 18, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "If you're looking for a lightweight running shoe, the VaporMax Flyknit from Nike delivers with flying colors. It's comfortable and versatile, making it a value-oriented trainer.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Vapormax", id, 2, 269.99, "Red", new ArrayList<Integer>(Arrays.asList(11,12,13)), 2.41, 10, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "If you're looking for a lightweight running shoe, the VaporMax Flyknit from Nike delivers with flying colors. It's comfortable and versatile, making it a value-oriented trainer.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Kobe 6", id, 2, 249.99, "Black", new ArrayList<Integer>(Arrays.asList(7,8,10,11,12)), 4.9245, 51, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Kobe Bean Bryant was an American professional basketball player. A shooting guard, he spent his entire 20-year career with the Los Angeles Lakers.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), true));
        productsMap.put(id,new Product("Kobe 6", id, 2, 249.99, "Green", new ArrayList<Integer>(Arrays.asList(7,8,10,11,12)), 4.14, 43, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Kobe Bean Bryant was an American professional basketball player. A shooting guard, he spent his entire 20-year career with the Los Angeles Lakers.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));
        productsMap.put(id,new Product("Kobe 6", id, 2, 249.99, "Red", new ArrayList<Integer>(Arrays.asList(7,8,10,11,12)), 4.631, 65, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Kobe Bean Bryant was an American professional basketball player. A shooting guard, he spent his entire 20-year career with the Los Angeles Lakers.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));

        productsMap.put(id,new Product("LeBron 9", id, 2, 265.99, "Black", new ArrayList<Integer>(Arrays.asList(11,12)), 4.5133, 123, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "LeBron James is an American professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). Nicknamed \"King James\", he is often compared to Michael Jordan in debates over the greatest basketball player ever.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), true));
        productsMap.put(id,new Product("LeBron 9", id, 2, 265.99, "Blue", new ArrayList<Integer>(Arrays.asList(11,12)), 4.7134, 100, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "LeBron James is an American professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). Nicknamed \"King James\", he is often compared to Michael Jordan in debates over the greatest basketball player ever.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));
        productsMap.put(id,new Product("LeBron 9", id, 2, 265.99, "Orange", new ArrayList<Integer>(Arrays.asList(11,12)), 4.1244, 120, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "LeBron James is an American professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). Nicknamed \"King James\", he is often compared to Michael Jordan in debates over the greatest basketball player ever.", new ArrayList<>(Arrays.asList("High-top","Synthetic material")), false));

        productsMap.put(id,new Product("Air Max Deluxe", id, 2, 269.99, "White", new ArrayList<Integer>(Arrays.asList(10,11,12)), 3.4124, 28, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "With a design inspired by the Air Max 99, the Nike Air Max Deluxe features a flowing \"wave\" design and lightweight materials. They have a breathable fabric upper, visible Max Air unit, heel counter, and a durable rubber outsole.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), true));
        productsMap.put(id,new Product("Air Max Deluxe", id, 2, 269.99, "Black", new ArrayList<Integer>(Arrays.asList(8,11,12)), 3.8141, 13, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "With a design inspired by the Air Max 99, the Nike Air Max Deluxe features a flowing \"wave\" design and lightweight materials. They have a breathable fabric upper, visible Max Air unit, heel counter, and a durable rubber outsole.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), false));
        productsMap.put(id,new Product("Air Max Deluxe", id, 2, 269.99, "Blue", new ArrayList<Integer>(Arrays.asList(7,11)), 4.13, 7, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "With a design inspired by the Air Max 99, the Nike Air Max Deluxe features a flowing \"wave\" design and lightweight materials. They have a breathable fabric upper, visible Max Air unit, heel counter, and a durable rubber outsole.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), false));

        productsMap.put(id,new Product("Air Max Plus", id, 2, 215.59, "Black", new ArrayList<Integer>(Arrays.asList(7,8,12)), 3.562635, 47, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Nike Air Max Plus gives you a tuned Nike Air experience that offers premium stability and unbelievable cushioning. Bringing no-worry beach life to the city, the supportive midfoot arch draws inspiration from a whale's tail.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), true));
        productsMap.put(id,new Product("Air Max Plus", id, 2, 215.59, "White", new ArrayList<Integer>(Arrays.asList(7,8,12)), 3.511243, 32, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Nike Air Max Plus gives you a tuned Nike Air experience that offers premium stability and unbelievable cushioning. Bringing no-worry beach life to the city, the supportive midfoot arch draws inspiration from a whale's tail.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), false));
        productsMap.put(id,new Product("Air Max Plus", id, 2, 215.59, "Blue", new ArrayList<Integer>(Arrays.asList(7,8,12)), 4.1412, 51, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Nike Air Max Plus gives you a tuned Nike Air experience that offers premium stability and unbelievable cushioning. Bringing no-worry beach life to the city, the supportive midfoot arch draws inspiration from a whale's tail.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), false));

        // Adidas shoes
        productsMap.put(id,new Product("Yeezy Boost 350", id, 3, 530.99, "Grey", new ArrayList<Integer>(Arrays.asList(7,8,12)), 3.535, 39, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 350 features an upper composed of re-engineered Primeknit. The post-dyed monofilament side stripe is woven into the upper. Reflective threads are woven into the laces.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Yeezy Boost 350", id, 3, 530.99, "Black", new ArrayList<Integer>(Arrays.asList(12)), 3.99572, 29, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 350 features an upper composed of re-engineered Primeknit. The post-dyed monofilament side stripe is woven into the upper. Reflective threads are woven into the laces.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Yeezy Boost 350", id, 3, 530.99, "Blue", new ArrayList<Integer>(Arrays.asList(8,10,12)), 4.626, 15, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 350 features an upper composed of re-engineered Primeknit. The post-dyed monofilament side stripe is woven into the upper. Reflective threads are woven into the laces.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Yeezy Boost 380", id, 3, 320.59, "White", new ArrayList<Integer>(Arrays.asList(12)), 4.525, 19, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 380 features an upper composed of multi-toned re-engineered Primeknit. The translucent monofilament window is woven into the upper, and the sock-like construction provides a snug fit and allows you to wear with or without laces.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), true));
        productsMap.put(id,new Product("Yeezy Boost 380", id, 3, 320.59, "Purple", new ArrayList<Integer>(Arrays.asList(8,12)), 4.425, 19, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 380 features an upper composed of multi-toned re-engineered Primeknit. The translucent monofilament window is woven into the upper, and the sock-like construction provides a snug fit and allows you to wear with or without laces.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), false));
        productsMap.put(id,new Product("Yeezy Boost 380", id, 3, 320.59, "Blue", new ArrayList<Integer>(Arrays.asList(7,12)), 4.525, 19, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 380 features an upper composed of multi-toned re-engineered Primeknit. The translucent monofilament window is woven into the upper, and the sock-like construction provides a snug fit and allows you to wear with or without laces.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), false));

        productsMap.put(id,new Product("Yeezy Boost 500", id, 3, 350.99, "Grey", new ArrayList<Integer>(Arrays.asList(7,8,12)), 4.14124, 49, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Developed by Kanye West, the Adidas Yeezy 500 is a sporty and stylish model. They are crafted with a combination of premium suede, leather, and mesh.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), true));
        productsMap.put(id,new Product("Yeezy Boost 500", id, 3, 350.99, "White", new ArrayList<Integer>(Arrays.asList(12)), 4.4124, 9, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Developed by Kanye West, the Adidas Yeezy 500 is a sporty and stylish model. They are crafted with a combination of premium suede, leather, and mesh.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), false));
        productsMap.put(id,new Product("Yeezy Boost 500", id, 3, 350.99, "Black", new ArrayList<Integer>(Arrays.asList(8,12)), 3.3525, 29, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Developed by Kanye West, the Adidas Yeezy 500 is a sporty and stylish model. They are crafted with a combination of premium suede, leather, and mesh.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), false));

        productsMap.put(id,new Product("Yeezy Boost 700", id, 3, 450.58, "Red", new ArrayList<Integer>(Arrays.asList(7,8,10,12)), 3.41, 15, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 700 features an upper composed of suede overlays and premium leather with mesh underlays and reflective heel and Three Stripe details. The full-length drop in boost midsole provides comfort and stability.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), true));
        productsMap.put(id,new Product("Yeezy Boost 700", id, 3, 450.58, "Blue", new ArrayList<Integer>(Arrays.asList(7,8,10,12)), 3.00, 2, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 700 features an upper composed of suede overlays and premium leather with mesh underlays and reflective heel and Three Stripe details. The full-length drop in boost midsole provides comfort and stability.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), false));
        productsMap.put(id,new Product("Yeezy Boost 700", id, 3, 450.58, "Grey", new ArrayList<Integer>(Arrays.asList(7,8,10,12)), 4.00, 1, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Boost 700 features an upper composed of suede overlays and premium leather with mesh underlays and reflective heel and Three Stripe details. The full-length drop in boost midsole provides comfort and stability.", new ArrayList<>(Arrays.asList("Low-top","Limited edition")), false));

        productsMap.put(id,new Product("Yeezy Boost 750", id, 3, 625.99, "Black", new ArrayList<Integer>(Arrays.asList(7,8,12)), 3.562635, 47, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The high-top sneaker features a full suede upper, dynamic mid-foot strap, full zipper running up the back heel, perforated vamp and a Boost cushioned sole.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), true));
        productsMap.put(id,new Product("Yeezy Boost 750", id, 3, 625.99, "Grey", new ArrayList<Integer>(Arrays.asList(7,8,11,12)), 3.2524, 24, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The high-top sneaker features a full suede upper, dynamic mid-foot strap, full zipper running up the back heel, perforated vamp and a Boost cushioned sole.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), false));
        productsMap.put(id,new Product("Yeezy Boost 750", id, 3, 625.99, "Brown", new ArrayList<Integer>(Arrays.asList(8,12)), 4.462, 27, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The high-top sneaker features a full suede upper, dynamic mid-foot strap, full zipper running up the back heel, perforated vamp and a Boost cushioned sole.", new ArrayList<>(Arrays.asList("High-top","Limited edition")), false));

        productsMap.put(id,new Product("Yeezy Slides", id, 3, 200.99, "Orange", new ArrayList<Integer>(Arrays.asList(7,8,10,12)), 4.333333, 32, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Slide features injected EVA foam to provide lightweight durability, while the soft top layer in the footbed offers immediate step in comfort. The outsole utilizes grooves for optimal flexibility and traction.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Yeezy Slides", id, 3, 200.99, "Green", new ArrayList<Integer>(Arrays.asList(10,12)), 4.646665, 14, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Slide features injected EVA foam to provide lightweight durability, while the soft top layer in the footbed offers immediate step in comfort. The outsole utilizes grooves for optimal flexibility and traction.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Yeezy Slides", id, 3, 200.99, "White", new ArrayList<Integer>(Arrays.asList(7,12)), 4.234, 18, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Yeezy Slide features injected EVA foam to provide lightweight durability, while the soft top layer in the footbed offers immediate step in comfort. The outsole utilizes grooves for optimal flexibility and traction.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Yeezy Foam Runner", id, 3, 320.99, "White", new ArrayList<Integer>(Arrays.asList(7,12)), 4.866, 154, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Foam Runner is comprised of a single piece of unique Yeezy material that blends harvested algae with adidas EVA materials. Its aerodynamic design features a medley of holes and ridges that take influence from the Yeezy 700.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Yeezy Foam Runner", id, 3, 320.99, "Black", new ArrayList<Integer>(Arrays.asList(10,12)), 4.76877, 39, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Foam Runner is comprised of a single piece of unique Yeezy material that blends harvested algae with adidas EVA materials. Its aerodynamic design features a medley of holes and ridges that take influence from the Yeezy 700.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Yeezy Foam Runner", id, 3, 320.99, "Yellow", new ArrayList<Integer>(Arrays.asList(9,11,12)), 4.77775, 67, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Foam Runner is comprised of a single piece of unique Yeezy material that blends harvested algae with adidas EVA materials. Its aerodynamic design features a medley of holes and ridges that take influence from the Yeezy 700.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Pharrell", id, 3, 210.79, "White", new ArrayList<Integer>(Arrays.asList(7,8)), 3.4567, 9, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "With a knit upper, adidas Pharrell shoes hug your feet like a sock and provide a snug fit. The flexible material reacts well to movement and is engineered to support your feet no matter what.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Pharrell", id, 3, 210.79, "Black", new ArrayList<Integer>(Arrays.asList(10,12)), 4.356, 11, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "With a knit upper, adidas Pharrell shoes hug your feet like a sock and provide a snug fit. The flexible material reacts well to movement and is engineered to support your feet no matter what.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Pharrell", id, 3, 210.79, "Green", new ArrayList<Integer>(Arrays.asList(9,11,12)), 4.04674, 23, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "With a knit upper, adidas Pharrell shoes hug your feet like a sock and provide a snug fit. The flexible material reacts well to movement and is engineered to support your feet no matter what.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("NMD R1", id, 3, 190.99, "White", new ArrayList<Integer>(Arrays.asList(7,8,10,12)), 4.9273, 26, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The adidas NMD R1 is also known as the adidas NMD Runner. It is a low-top sneaker that features Primeknit, mesh, or neoprene above a Boost sole.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("NMD R1", id, 3, 190.99, "Red", new ArrayList<Integer>(Arrays.asList(9,11,12)), 4.865, 25, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The adidas NMD R1 is also known as the adidas NMD Runner. It is a low-top sneaker that features Primeknit, mesh, or neoprene above a Boost sole.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("NMD R1", id, 3, 190.99, "Black", new ArrayList<Integer>(Arrays.asList(10,11,12)), 3.996, 27, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The adidas NMD R1 is also known as the adidas NMD Runner. It is a low-top sneaker that features Primeknit, mesh, or neoprene above a Boost sole.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        productsMap.put(id,new Product("Ultraboost", id, 3, 140.99, "White", new ArrayList<Integer>(Arrays.asList(10)), 5.0000, 1, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Adidas Ultraboost is a max-cushioned, heavy-duty trainer for easy and recovery runs. It has a stable ride and is one of the most comfortable running shoes on the market.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), true));
        productsMap.put(id,new Product("Ultraboost", id, 3, 140.99, "Black", new ArrayList<Integer>(Arrays.asList(10)), 2.854, 5, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Adidas Ultraboost is a max-cushioned, heavy-duty trainer for easy and recovery runs. It has a stable ride and is one of the most comfortable running shoes on the market.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));
        productsMap.put(id,new Product("Ultraboost", id, 3, 140.99, "Yellow", new ArrayList<Integer>(Arrays.asList(10)), 3.657, 3, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Adidas Ultraboost is a max-cushioned, heavy-duty trainer for easy and recovery runs. It has a stable ride and is one of the most comfortable running shoes on the market.", new ArrayList<>(Arrays.asList("Low-top","Synthetic material")), false));

        // Vans shoes
        productsMap.put(id,new Product("Old skool", id, 4, 120.99, "Black", new ArrayList<Integer>(Arrays.asList(7,8,12)), 3.562635, 47, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Constructed with durable suede and canvas uppers in a range of fresh colorways, the Old Skool pays homage to the Vans brand.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), true));
        productsMap.put(id,new Product("Old skool", id, 4, 120.99, "Green", new ArrayList<Integer>(Arrays.asList(7,8,10,12)), 3.333, 65, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Constructed with durable suede and canvas uppers in a range of fresh colorways, the Old Skool pays homage to the Vans brand.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));
        productsMap.put(id,new Product("Old skool", id, 4, 120.99, "Blue", new ArrayList<Integer>(Arrays.asList(7,8,12)), 3.98229, 29, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Constructed with durable suede and canvas uppers in a range of fresh colorways, the Old Skool pays homage to the Vans brand.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));

        productsMap.put(id,new Product("Authentic", id, 4, 130.99, "Black", new ArrayList<Integer>(Arrays.asList(7,8)), 1.9421, 31, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Born in Anaheim, California in 1966, the Authentic is the original Vans heritage style. Originally know as Vans #44 Deck Shoes, the Authentic became an immediate cult icon, and has embodied our “Off The Wall” attitude ever since. Constructed with a simple low top, lace-up profile, this classic shoe also features sturdy canvas uppers, metal eyelets, and signature rubber waffle outsoles.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), true));
        productsMap.put(id,new Product("Authentic", id, 4, 130.99, "Blue", new ArrayList<Integer>(Arrays.asList(9,12)), 2.124, 124, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Born in Anaheim, California in 1966, the Authentic is the original Vans heritage style. Originally know as Vans #44 Deck Shoes, the Authentic became an immediate cult icon, and has embodied our “Off The Wall” attitude ever since. Constructed with a simple low top, lace-up profile, this classic shoe also features sturdy canvas uppers, metal eyelets, and signature rubber waffle outsoles.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));
        productsMap.put(id,new Product("Authentic", id, 4, 130.99, "Green", new ArrayList<Integer>(Arrays.asList(7,8,12)), 2.4124, 25, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Born in Anaheim, California in 1966, the Authentic is the original Vans heritage style. Originally know as Vans #44 Deck Shoes, the Authentic became an immediate cult icon, and has embodied our “Off The Wall” attitude ever since. Constructed with a simple low top, lace-up profile, this classic shoe also features sturdy canvas uppers, metal eyelets, and signature rubber waffle outsoles.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));

        productsMap.put(id,new Product("SK8-Hi", id, 4, 135.99, "Black", new ArrayList<Integer>(Arrays.asList(9,12)), 3.214, 31, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Introduced in the early 70's, the Vans SK8 Hi was responsible for the reduced number of ankle injuries in the skating scene with the extra padded ankle support, but its popularity has grown across different cultural scenes.", new ArrayList<>(Arrays.asList("High-top","Low-top","Premium leather")), true));
        productsMap.put(id,new Product("SK8-Hi", id, 4, 135.99, "Orange", new ArrayList<Integer>(Arrays.asList(7,11)), 4.5124, 82, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Introduced in the early 70's, the Vans SK8 Hi was responsible for the reduced number of ankle injuries in the skating scene with the extra padded ankle support, but its popularity has grown across different cultural scenes.", new ArrayList<>(Arrays.asList("High-top","Low-top","Premium leather")), false));
        productsMap.put(id,new Product("SK8-Hi", id, 4, 135.99, "Pink", new ArrayList<Integer>(Arrays.asList(10,11,12)), 4.52174, 49, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Introduced in the early 70's, the Vans SK8 Hi was responsible for the reduced number of ankle injuries in the skating scene with the extra padded ankle support, but its popularity has grown across different cultural scenes.", new ArrayList<>(Arrays.asList("High-top","Low-top","Premium leather")), false));

        productsMap.put(id,new Product("Slip-on Checkerboard", id, 4, 135.99, "Black", new ArrayList<Integer>(Arrays.asList(7,8,11,12)), 3.5124, 24, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Classic Slip-On has a low profile, slip-on canvas upper with all-over checker print, elastic side accents, Vans flag label and Vans original Waffle Outsole.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), true));
        productsMap.put(id,new Product("Slip-on Checkerboard", id, 4, 135.99, "Green", new ArrayList<Integer>(Arrays.asList(7)), 3.51241, 42, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Classic Slip-On has a low profile, slip-on canvas upper with all-over checker print, elastic side accents, Vans flag label and Vans original Waffle Outsole.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));
        productsMap.put(id,new Product("Slip-on Checkerboard", id, 4, 135.99, "Yellow", new ArrayList<Integer>(Arrays.asList(7,8,12)), 3.421124, 63, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Classic Slip-On has a low profile, slip-on canvas upper with all-over checker print, elastic side accents, Vans flag label and Vans original Waffle Outsole.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));

        productsMap.put(id,new Product("Slip-on Classic", id, 4, 140.99, "White", new ArrayList<Integer>(Arrays.asList(7,8,9,10,1112)), 4.123, 123, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "A low profile, slip-on shoe, the Vans Classic Slip-On has elastic side accents and padded collars for extra comfort. It also features the Vans flag label and signature waffle outsoles for firmer grip.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), true));
        productsMap.put(id,new Product("Slip-on Classic", id, 4, 140.99, "Blue", new ArrayList<Integer>(Arrays.asList(10,12)), 3.45412, 32, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "A low profile, slip-on shoe, the Vans Classic Slip-On has elastic side accents and padded collars for extra comfort. It also features the Vans flag label and signature waffle outsoles for firmer grip.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));
        productsMap.put(id,new Product("Slip-on Classic", id, 4, 140.99, "Red", new ArrayList<Integer>(Arrays.asList(7,8,10,12)), 4.451, 94, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "A low profile, slip-on shoe, the Vans Classic Slip-On has elastic side accents and padded collars for extra comfort. It also features the Vans flag label and signature waffle outsoles for firmer grip.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));
        
        productsMap.put(id,new Product("Slip-on Trek", id, 4, 140.99, "White", new ArrayList<Integer>(Arrays.asList(12)), 4.124, 124, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Trek Slip-On takes the Classic Slip-On silhouette to a whole new level. The Trek Slip-On combines all the Vans DNA that you know and love with a durable, single piece injected construction, deconstructed checkerboard drainage holes for breathability, and an oversized reverse waffle sole for incredible traction in any situation.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), true));
        productsMap.put(id,new Product("Slip-on Trek", id, 4, 140.99, "Black", new ArrayList<Integer>(Arrays.asList(7,8,12)), 2.3414, 42, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Trek Slip-On takes the Classic Slip-On silhouette to a whole new level. The Trek Slip-On combines all the Vans DNA that you know and love with a durable, single piece injected construction, deconstructed checkerboard drainage holes for breathability, and an oversized reverse waffle sole for incredible traction in any situation.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));
        productsMap.put(id,new Product("Slip-on Trek", id, 4, 140.99, "Red", new ArrayList<Integer>(Arrays.asList(7)), 4.213, 102, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Trek Slip-On takes the Classic Slip-On silhouette to a whole new level. The Trek Slip-On combines all the Vans DNA that you know and love with a durable, single piece injected construction, deconstructed checkerboard drainage holes for breathability, and an oversized reverse waffle sole for incredible traction in any situation.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));

        productsMap.put(id,new Product("Slip-on Stackform", id, 4, 195.99, "White", new ArrayList<Integer>(Arrays.asList(11,12)), 2.5341143, 54, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Vans Rib Knit Slip-On Stackform Shoes refreshes our original slip-on silhouette with an even chunkier take on the platform aesthetic. Constructed with a 34 mm sidewall height, this platform shoe elevates a classic favorite while bringing a new “Off The Wall” style to your look.", new ArrayList<>(Arrays.asList("Limited edition","Premium leather")), true));
        productsMap.put(id,new Product("Slip-on Stackform", id, 4, 195.99, "Black", new ArrayList<Integer>(Arrays.asList(12)), 4.76324, 48, true, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Vans Rib Knit Slip-On Stackform Shoes refreshes our original slip-on silhouette with an even chunkier take on the platform aesthetic. Constructed with a 34 mm sidewall height, this platform shoe elevates a classic favorite while bringing a new “Off The Wall” style to your look.", new ArrayList<>(Arrays.asList("Limited edition","Premium leather")), false));
        productsMap.put(id,new Product("Slip-on Stackform", id, 4, 195.99, "Red", new ArrayList<Integer>(Arrays.asList(10,12)), 2.4542, 97, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Vans Rib Knit Slip-On Stackform Shoes refreshes our original slip-on silhouette with an even chunkier take on the platform aesthetic. Constructed with a 34 mm sidewall height, this platform shoe elevates a classic favorite while bringing a new “Off The Wall” style to your look.", new ArrayList<>(Arrays.asList("Limited edition","Premium leather")), false));

        productsMap.put(id,new Product("Anaheim Factory", id, 4, 165.99, "Blue", new ArrayList<Integer>(Arrays.asList(7,8,12)), 4.4315, 12, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Anaheim Factory includes throwback details like the original style number and color palette or reissued prints, higher glossed foxing tape, cotton laces, original drill lining weight, and suede and textile uppers to complete the look.", new ArrayList<>(Arrays.asList("Limited edition","Premium leather")), true));
        productsMap.put(id,new Product("Anaheim Factory", id, 4, 165.99, "Purple", new ArrayList<Integer>(Arrays.asList(7,10)), 4.1244, 11, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Anaheim Factory includes throwback details like the original style number and color palette or reissued prints, higher glossed foxing tape, cotton laces, original drill lining weight, and suede and textile uppers to complete the look.", new ArrayList<>(Arrays.asList("Limited edition","Premium leather")), false));
        productsMap.put(id,new Product("Anaheim Factory", id, 4, 165.99, "Black", new ArrayList<Integer>(Arrays.asList(9,12)), 3.124443, 17, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "The Anaheim Factory includes throwback details like the original style number and color palette or reissued prints, higher glossed foxing tape, cotton laces, original drill lining weight, and suede and textile uppers to complete the look.", new ArrayList<>(Arrays.asList("Limited edition","Premium leather")), false));

        productsMap.put(id,new Product("Exo", id, 4, 175.99, "White", new ArrayList<Integer>(Arrays.asList(9,11)), 3.124412, 31, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Armed with a co-molded UltraCush midsole, updated RapidWeld detailing, a lightweight, die-cut rubber outsole, and a breathable Old Skool-inspired upper, this is the UltraRange—evolved. The UltraRange EXO is made with sturdy textile and synthetic uppers.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), true));
        productsMap.put(id,new Product("Exo", id, 4, 175.99, "Black", new ArrayList<Integer>(Arrays.asList(7,8,12)), 4.214124, 35, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Armed with a co-molded UltraCush midsole, updated RapidWeld detailing, a lightweight, die-cut rubber outsole, and a breathable Old Skool-inspired upper, this is the UltraRange—evolved. The UltraRange EXO is made with sturdy textile and synthetic uppers.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));
        productsMap.put(id,new Product("Exo", id, 4, 175.99, "Green", new ArrayList<Integer>(Arrays.asList(7)), 2.5124, 35, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Armed with a co-molded UltraCush midsole, updated RapidWeld detailing, a lightweight, die-cut rubber outsole, and a breathable Old Skool-inspired upper, this is the UltraRange—evolved. The UltraRange EXO is made with sturdy textile and synthetic uppers.", new ArrayList<>(Arrays.asList("Low-top","Premium leather")), false));

        productsMap.put(id,new Product("Exo High", id, 4, 199.99, "Black", new ArrayList<Integer>(Arrays.asList(11,12)), 4.12421, 99, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Activity-inspired, purpose-built, and designed to protect you from the elements, the UltraRange Exo Hi MTE-1 blends the comfort and get-you-there features of the UltraRange family with the protection from the elements that only the MTE franchise can provide.", new ArrayList<>(Arrays.asList("High-top","Premium leather")), true));
        productsMap.put(id,new Product("Exo High", id, 4, 199.99, "Green", new ArrayList<Integer>(Arrays.asList(7,8)), 3.76142, 85, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Activity-inspired, purpose-built, and designed to protect you from the elements, the UltraRange Exo Hi MTE-1 blends the comfort and get-you-there features of the UltraRange family with the protection from the elements that only the MTE franchise can provide.", new ArrayList<>(Arrays.asList("High-top","Premium leather")), false));
        productsMap.put(id,new Product("Exo High", id, 4, 199.99, "Red", new ArrayList<Integer>(Arrays.asList(7,8,11)), 3.5152, 40, false, new ArrayList<String>(Arrays.asList(id+"_1",id+"_2",id++ +"_3")), "Activity-inspired, purpose-built, and designed to protect you from the elements, the UltraRange Exo Hi MTE-1 blends the comfort and get-you-there features of the UltraRange family with the protection from the elements that only the MTE franchise can provide.", new ArrayList<>(Arrays.asList("High-top","Premium leather")), false));

        // add all to database
        for(long i = initialId; i < id; i++){
            products.document(i+"").set(Objects.requireNonNull(productsMap.get(i)));
        }

    }
}
